# Generated by Django 2.2.4 on 2019-08-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0005_auto_20190811_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='type',
            field=models.CharField(max_length=16),
        ),
    ]
