# Generated by Django 2.2.3 on 2019-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('iata', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('elevation_ft', models.IntegerField(default=0)),
                ('continent', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=16)),
                ('municipality', models.CharField(max_length=128)),
                ('scheduled_service', models.BooleanField(default=False)),
            ],
        ),
    ]
