# Generated by Django 2.2.4 on 2019-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_auto_20190811_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_longitude',
            field=models.FloatField(blank=True),
        ),
    ]
