# Generated by Django 2.2.4 on 2019-08-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0009_auto_20190811_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='elevation_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='scheduled_service',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='frequency',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='closed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_displaced_threshold_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_elevation_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_heading_true',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='he_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_displaced_threshold_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_elevation_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_heading_true',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='le_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='length_ft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='lighted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='runway',
            name='width_ft',
            field=models.IntegerField(null=True),
        ),
    ]
