# Generated by Django 2.2.4 on 2019-08-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0011_auto_20190812_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runway',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='runway',
            name='he_heading_true',
        ),
        migrations.RemoveField(
            model_name='runway',
            name='le_heading_true',
        ),
        migrations.RemoveField(
            model_name='runway',
            name='lighted',
        ),
        migrations.AlterField(
            model_name='runway',
            name='surface',
            field=models.CharField(max_length=32),
        ),
    ]
