# Generated by Django 2.2.4 on 2019-08-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0013_auto_20190818_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runway',
            old_name='he_displaced_threshold_ft',
            new_name='he_displaced_ft',
        ),
        migrations.RenameField(
            model_name='runway',
            old_name='le_displaced_threshold_ft',
            new_name='le_displaced_ft',
        ),
    ]
