# Generated by Django 2.2.4 on 2019-09-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0014_auto_20190818_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='icao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airports.Airport'),
        ),
        migrations.AlterField(
            model_name='runway',
            name='icao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airports.Airport'),
        ),
    ]
