# Generated by Django 2.2.4 on 2019-09-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0015_auto_20190929_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='icao',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='runway',
            name='icao',
            field=models.CharField(max_length=8),
        ),
    ]
