# Generated by Django 2.2.4 on 2019-08-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0008_auto_20190811_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='runway',
            name='surface',
            field=models.CharField(max_length=64),
        ),
    ]
